version: "3"

services:
    mysql:
        build:
            context: ./mysql
        env_file:
            - mysql.env
        environment:
            - MARIADB_DATABASE=wordpress
    wordpress:
        build:
            context: ./wordpress
        depends_on:
            - "mysql"
        env_file:
            - wordpress.env
        environment:
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_NAME=wordpress
        ports:
            - "80:80"
    phpmyadmin:
        build:
            context: ./phpmyadmin
        depends_on:
            - "mysql"
        environment:
            - PMA_HOST=mysql
        ports:
            - "8080:80"
